#ifndef PLATFORMER_REFLECT_H
#define PLATFORMER_REFLECT_H

#include <oak/oak_def.h>

const uint REFLECT_CAMERA_FOLLOW = REFLECT_LAST + 1;
const uint REFLECT_GROUND_CHECK = REFLECT_LAST + 2;
const uint REFLECT_MOVEMENT = REFLECT_LAST + 3;

#endif